const DASHBOARD_AUTH_KEY = "DASHBOARD_AUTH_KEY";
const IS_LOGGED_IN = "IS_LOGGED_IN";
const INITIAL_USER_STATE = null;
const USER_INFO_LOCAL_STORAGE_KEY = "USER_INFO_LOCAL_STORAGE_KEY";
export {
  DASHBOARD_AUTH_KEY,
  IS_LOGGED_IN,
  INITIAL_USER_STATE,
  USER_INFO_LOCAL_STORAGE_KEY
};
